# Base image
FROM node:16


# Set the working directory
WORKDIR /frontend

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the production-ready app
RUN npm run build

FROM nginx:1.21

# Copy the build output to replace the default nginx contents.
COPY --from=0 /frontend/build /usr/share/nginx/html

COPY nginx.conf etc/nginx/nginx.conf

# Expose the desired port
EXPOSE 3000

# Set the command to run the app
CMD ["nginx", "-g", "daemon off;"]
